import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { Box, Typography } from "@mui/material";

import Header from "../components/Header";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="flex flex-col w-full h-screen px-6 pt-10 mx-auto max-w-7xl">
        <Box>
          <Typography variant="h4">参考リンク</Typography>
          <Box p={4} display="flex" flexDirection={"column"}>
            <Link href="https://react-icons.github.io/react-icons/">
              react-icons
            </Link>
            <Link href="https://github.com/alan2207/bulletproof-react">
              bulletproof-react
            </Link>
          </Box>
        </Box>
        <Box>
          <Typography variant="h4">アプリリンク</Typography>
          <Box p={4} display="flex" flexDirection={"column"}>
            <Link href="/airbnb">Airbnb</Link>
            <Link href="/youtube">Youtube</Link>
          </Box>
        </Box>
      </main>
    </div>
  );
};

export default Home;
